---
title: "l2p2"
author: "Thiago Cunha Montenegro"
output: 
    flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(RColorBrewer)
```
```{r read, include=FALSE}
    respostas = read_csv(here::here("data/enade-ufcg-2017.csv"),
                     col_types = "cccdccdddc")
    medias = respostas %>% 
        filter(categoria != "Outros") %>% 
        group_by(NOME_CURSO, categoria) %>% 
        summarise(media = mean(media))
 
   
    departamentos <- respostas %>%
        mutate(depto = case_when(
            NOME_CURSO %in% c('Engenharia (13445)','Engenharia de Produção (79570)', 'Engenharia Mecânica (13442)', 'Engenharia Química (13441)', 'Engenharia (118562)') ~ 'CCT',
            NOME_CURSO %in% c('Engenharia (13444)', 'Engenharia Civil (13439)','Engenharia de Alimentos (112294)', 'Arquitetura e Urbanismo (1129147)') ~ 'CTRN', NOME_CURSO %in% c('Geografia (Licenciatura) (120777)', 'História (Licenciatura) (13449)', 'Letras-Português (Licenciatura) (1158116)', 'Pedagogia (Licenciatura) (13452)') ~ 'CH',NOME_CURSO %in% c('Geografia (Licenciatura) (13407)','História (Licenciatura) (13405)', 'Letras-Português (Licenciatura) (1160083)','Pedagogia (Licenciatura) (13410)', 'Química (Licenciatura) (1152881)', 'Ciências Biológicas (Licenciatura) (1152882)') ~ 'CFP',NOME_CURSO %in% c('Engenharia (1106561)', 'Engenharia de Produção (1106578)', 'Ciências Sociais (Licenciatura) (1106595)') ~ 'CDSA', NOME_CURSO %in% c('Química (Licenciatura) (99808)', 'Ciências Biológicas (Licenciatura) (99804)') ~ 'CES',
        NOME_CURSO %in% c('Engenharia Elétrica (13438)', 'Ciência Da Computação (Bacharelado) (13446)') ~ 'CEEI',
        NOME_CURSO %in% c('Engenharia Florestal (13456)', 'Ciências Biológicas (Licenciatura) (99802)') ~ 'CSTR',
        NOME_CURSO %in% c('Engenharia Ambiental (112282)') ~ 'CCTA'))
    
    media_por_departamento <- departamentos %>%
            group_by(depto, categoria,tema) %>%
            summarise(media_depto = mean(media),
                      maior = max(media),
                      menor = min(media))
    
    glimpse(respostas)
```


Page 1
========================================================
Column {data-width = 900}
-------------------------------------------------------
### Chart 1

```{r}
media_por_departamento %>%
        filter(categoria != 'Outros') %>%
        ggplot(aes(reorder(tema,media_depto), y = media_depto, color = depto)) +
        geom_jitter(width = .1, alpha = 0.75) +
        labs(x = '', y = 'Avaliação numa escala de 1 a 6', title = 'Todas as Respostas', subtitle = 'Cada Departamento uma Cor')+
        facet_grid(reorder(categoria, media_depto) ~ ., scales = 'free_y') +
        theme(legend.position = 'bottom') +
        coord_flip() 

```

```{r}
d = media_por_departamento %>%
        group_by(depto,categoria) %>%
        summarise(media_depto = mean(media_depto))

d %>% plot_ly(type = 'scatter',
              y = ~media_depto, 
              x = ~categoria,
              text = ~paste("Departamento: ", d$depto,
                           "<br>Categoria: ", d$categoria,
                           "<br>Media: ", d$media_depto),
              hovernfo = 'text', color = ~d$depto, colors = 'Set1', size = 1) %>% layout(title = 'Avaliações dos Departamentos entre os Temas',
        yaxis = list(title = 'Média Departamento'),                                             xaxis = list(title = 'Tema de Avaliação'))
```
##Sera que a avalição do departamento que possuem maior infraestutura, possuem melhores dados entre os outros temas de avaliação?

Sabendo que o departamento que possui maior avaliação em infraestrutura é o departamento CES, vamos comparar tal departamento com outros departamentos em relação
```{r}

ces = media_por_departamento %>%
                filter(categoria != 'Outros', depto == 'CES') %>%
                group_by(tema) %>%
                summarise(ces = mean(media_depto))

comparacao = media_por_departamento %>% 
    left_join(ces, by = "tema") %>% 
    mutate(diferenca = ces - media_depto, 
           maior_dif = maior - media_depto, 
           menor_dif = menor - media_depto)

```

```{r fig.height=12, fig.width=6}
comparacao %>% 
    filter(categoria != 'Outros') %>%
    ggplot(aes(reorder(tema, diferenca))) +
    geom_col(aes(y = diferenca, fill = diferenca > 0)) +
    facet_grid(reorder(categoria, -diferenca) ~ ., scales = 'free_y') +
    coord_flip()

```
